### ISSUE TITLE
Adders produce terrible coreir json/verilog due to wiring individual bits

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/mantle#100] opened 2018-08-02 17:58 UTC
How can we get adders to bulk wire arrays rather than wire individual bits? Is this fundamental to the magma backend?

Solutions are either
-Keep the current behavior and fix it up in a coreir pass
-fix on the magma/mantle side

I would push for the latter since I feel like this goes against the philosophy of our toolchain in which we want to maintain as much high level structure as possible for as long as possible. It seems like the wrong solution to blow out structure at this level and to build it back up at the coreir level.

Thoughts?

**Comment by leonardt** [comment] 2018-08-03 00:46
Can you point to the example to reproduce the bad verilog?

We recently added a way for implementations to define specialized implementations of functions. So, the coreir backend could provide a specialized implementation of Adders that  uses bulk connections.

I'm pretty sure this is an artifact of how Adders are implemented (as a the instancing and wiring up of individual FullAdder instances). This is a feature for the ice40 backend, since it makes good (specific) use of the available hardware primitives. The coreir implementation should be more generic and use the add primitive (with bulk connections).

**Comment by rdaly525** [comment] 2018-08-03 00:49
Specifically looking at the output of the coreir counters example.

**Comment by leonardt** [comment] 2018-08-03 01:15
So you're referring to the wiring up of individual bits for the input the add?

**Comment by leonardt** [comment] 2018-08-03 01:25
Fixed by https://github.com/phanrahan/magma/commit/b8278da0aa54ec301d1114edb81f7440e7f8aac7, the logic was actually already there but was getting short circuited by some anonymous (pesky) bit logic.

Here's an updated output .json for that counters example: https://github.com/phanrahan/mantle/commit/540d4569085b1c90eaa3de9ce80f80b0f37ace9b

Here are some other improvements in our test suite:
https://github.com/phanrahan/mantle/commit/cb7fffa54c3d0f47a99001e245ee8094eb0779d2

Closing this for now, let me know if there are other places we can improve the .json we are generating (examples are super helpful for these kinds of issues).

**Closed by leonardt** 2018-08-03 01:25 UTC
